import type { Metadata } from 'next';
import { Inter, Lora } from 'next/font/google';
import Link from 'next/link';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

const lora = Lora({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next APp',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className}`}>
        <header className='header'>
          <nav className='nav'>
            <Link href='/'>Home</Link>
            <Link href='/posts'>Posts</Link>
            <Link href='/about'>About</Link>
          </nav>
        </header>

        <main className='main'> {children}</main>
        <footer className={`footer ${lora.className}`}>
          © {new Date().getFullYear()} My Blog. All rights reserved.
        </footer>
      </body>
    </html>
  );
}
