import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import Header from './components/Header';
import SessionProvider from './SessionProvider';

import './globals.css';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/pages/api/auth/[...nextauth]';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  let session = await getServerSession(authOptions);
  return (
    <html lang="kr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-gray-50`}
      >
        <SessionProvider session={session}>
          <Header session={session} />
          <main className="mx-auto max-w-3xl py-8">{children}</main>
        </SessionProvider>
      </body>
    </html>
  );
}
